//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Start.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akrobatyka.
        /// </summary>
        public static string Acrobatics {
            get {
                return ResourceManager.GetString("Acrobatics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DODAJ POSTAĆ.
        /// </summary>
        public static string AddCharacter {
            get {
                return ResourceManager.GetString("AddCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwierzęta.
        /// </summary>
        public static string AnimalHandling {
            get {
                return ResourceManager.GetString("AnimalHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkana.
        /// </summary>
        public static string Arcana {
            get {
                return ResourceManager.GetString("Arcana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atletyka.
        /// </summary>
        public static string Athletics {
            get {
                return ResourceManager.GetString("Athletics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRÓĆ.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Piotr Hadam\source\repos\Start\Start\Images\background.jpg.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap background1 {
            get {
                object obj = ResourceManager.GetObject("background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap character_sheet {
            get {
                object obj = ResourceManager.GetObject("character_sheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\repos2\NewAttempt\DNDcharacters\Start\Images\character_sheet2.png.
        /// </summary>
        public static string CharacterSheet {
            get {
                return ResourceManager.GetString("CharacterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTA POSTACI.
        /// </summary>
        public static string CharactersList {
            get {
                return ResourceManager.GetString("CharactersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charyzma.
        /// </summary>
        public static string Charisma {
            get {
                return ResourceManager.GetString("Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WYBIERZ.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa.
        /// </summary>
        public static string Clas {
            get {
                return ResourceManager.GetString("Clas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kondycja.
        /// </summary>
        public static string Constitution {
            get {
                return ResourceManager.GetString("Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstęp.
        /// </summary>
        public static string Deception {
            get {
                return ResourceManager.GetString("Deception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUŃ.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zręczność.
        /// </summary>
        public static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WYJŚCIE.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Życie.
        /// </summary>
        public static string HitPoints {
            get {
                return ResourceManager.GetString("HitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intuicja.
        /// </summary>
        public static string Insight {
            get {
                return ResourceManager.GetString("Insight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inteligencja.
        /// </summary>
        public static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastraszanie.
        /// </summary>
        public static string Intimidation {
            get {
                return ResourceManager.GetString("Intimidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detektywistyka.
        /// </summary>
        public static string Investigation {
            get {
                return ResourceManager.GetString("Investigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiracja.
        /// </summary>
        public static string IsInspired {
            get {
                return ResourceManager.GetString("IsInspired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poziom.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZALOGUJ SIĘ.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Piotr Hadam\source\repos\Start\Start\Images\back2.jpg.
        /// </summary>
        public static string LoginBackground {
            get {
                return ResourceManager.GetString("LoginBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leczenie.
        /// </summary>
        public static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieniądze.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natura.
        /// </summary>
        public static string Nature {
            get {
                return ResourceManager.GetString("Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz jeszcze konta?.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percepcja.
        /// </summary>
        public static string Perception {
            get {
                return ResourceManager.GetString("Perception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydajność.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perswazja.
        /// </summary>
        public static string Persuasion {
            get {
                return ResourceManager.GetString("Persuasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasa.
        /// </summary>
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAREJESTRUJ SIĘ.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie konta.
        /// </summary>
        public static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religia.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAPISZ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zręczność Ręki.
        /// </summary>
        public static string SleightOfHand {
            get {
                return ResourceManager.GetString("SleightOfHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrożność.
        /// </summary>
        public static string Stealth {
            get {
                return ResourceManager.GetString("Stealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siła.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przetrwanie.
        /// </summary>
        public static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Piotr Hadam\source\repos\Start\Start\Images\title.png.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap title1 {
            get {
                object obj = ResourceManager.GetObject("title1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap title2 {
            get {
                object obj = ResourceManager.GetObject("title2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mądrość.
        /// </summary>
        public static string Wisdom {
            get {
                return ResourceManager.GetString("Wisdom", resourceCulture);
            }
        }
    }
}
